export const traducoes = {
  'pt-BR': {
    navbar: {
      sobre: 'Sobre',
      stack: 'Stack',
      projetos: 'Projetos',
      experiencia: 'Experiência',
      contato: 'Contato',
    },
    sobre: {
      titulo: 'Sobre Mim',
      localizacao: 'Localização',
      disponibilidade: 'Disponibilidade',
      email: 'Email',
      telefone: 'Telefone',
    },
    stack: {
      titulo: 'Stack Técnico',
      subtitulo: 'Tecnologias e ferramentas que utilizo',
      categorias: {
        backend: 'Backend',
        banco_dados: 'Banco de Dados',
        frontend: 'Frontend',
        devops: 'DevOps',
      },
      nivel: 'Nível',
    },
    projetos: {
      titulo: 'Projetos',
      subtitulo: 'Alguns dos meus trabalhos recentes',
      demo: 'Ver Demo',
      codigo: 'Ver Código',
      semLinks: 'Links em breve',
      tecnologias: 'Tecnologias',
    },
    experiencia: {
      titulo: 'Experiência Profissional',
      subtitulo: 'Minha trajetória profissional',
      atual: 'Atual',
      periodo: 'Período',
      tecnologias: 'Tecnologias',
    },
    contato: {
      titulo: 'Entre em Contato',
      subtitulo: 'Vamos conversar sobre seu projeto',
      nome: 'Nome',
      nomePlaceholder: 'Seu nome completo',
      email: 'Email',
      emailPlaceholder: 'seu@email.com',
      assunto: 'Assunto',
      assuntoPlaceholder: 'Sobre o que você quer falar?',
      mensagem: 'Mensagem',
      mensagemPlaceholder: 'Descreva seu projeto ou dúvida...',
      enviar: 'Enviar Mensagem',
      enviando: 'Enviando...',
      sucesso: 'Mensagem enviada com sucesso! Retornarei em breve.',
      erro: 'Erro ao enviar mensagem. Tente novamente.',
      erros: {
        nome: 'Nome deve ter entre 3 e 100 caracteres',
        email: 'Email inválido',
        assunto: 'Assunto deve ter entre 5 e 200 caracteres',
        mensagem: 'Mensagem deve ter entre 10 e 5000 caracteres',
      },
    },
    rodape: {
      desenvolvido: 'Desenvolvido com React + FastAPI',
      direitos: '© 2025 Argenis Lopez. Todos os direitos reservados.',
    },
    comum: {
      carregando: 'Carregando...',
      erro: 'Erro ao carregar dados',
      temaClaro: 'Tema Claro',
      temaEscuro: 'Tema Escuro',
    },
  },
  es: {
    navbar: {
      sobre: 'Sobre mí',
      stack: 'Stack',
      projetos: 'Proyectos',
      experiencia: 'Experiencia',
      contato: 'Contacto',
    },
    sobre: {
      titulo: 'Sobre Mí',
      localizacao: 'Ubicación',
      disponibilidade: 'Disponibilidad',
      email: 'Correo',
      telefone: 'Teléfono',
    },
    stack: {
      titulo: 'Stack Técnico',
      subtitulo: 'Tecnologías y herramientas que utilizo',
      categorias: {
        backend: 'Backend',
        banco_dados: 'Base de Datos',
        frontend: 'Frontend',
        devops: 'DevOps',
      },
      nivel: 'Nivel',
    },
    projetos: {
      titulo: 'Proyectos',
      subtitulo: 'Algunos de mis trabajos recientes',
      demo: 'Ver Demo',
      codigo: 'Ver Código',
      semLinks: 'Enlaces próximamente',
      tecnologias: 'Tecnologías',
    },
    experiencia: {
      titulo: 'Experiencia Profesional',
      subtitulo: 'Mi trayectoria profesional',
      atual: 'Actual',
      periodo: 'Período',
      tecnologias: 'Tecnologías',
    },
    contato: {
      titulo: 'Contáctame',
      subtitulo: 'Hablemos sobre tu proyecto',
      nome: 'Nombre',
      nomePlaceholder: 'Tu nombre completo',
      email: 'Correo',
      emailPlaceholder: 'tu@correo.com',
      assunto: 'Asunto',
      assuntoPlaceholder: '¿De qué quieres hablar?',
      mensagem: 'Mensaje',
      mensagemPlaceholder: 'Describe tu proyecto o duda...',
      enviar: 'Enviar Mensaje',
      enviando: 'Enviando...',
      sucesso: '¡Mensaje enviado con éxito! Te responderé pronto.',
      erro: 'Error al enviar mensaje. Inténtalo de nuevo.',
      erros: {
        nome: 'El nombre debe tener entre 3 y 100 caracteres',
        email: 'Correo inválido',
        assunto: 'El asunto debe tener entre 5 y 200 caracteres',
        mensagem: 'El mensaje debe tener entre 10 y 5000 caracteres',
      },
    },
    rodape: {
      desenvolvido: 'Desarrollado con React + FastAPI',
      direitos: '© 2025 Argenis Lopez. Todos los derechos reservados.',
    },
    comum: {
      carregando: 'Cargando...',
      erro: 'Error al cargar datos',
      temaClaro: 'Tema Claro',
      temaEscuro: 'Tema Oscuro',
    },
  },
  en: {
    navbar: {
      sobre: 'About',
      stack: 'Stack',
      projetos: 'Projects',
      experiencia: 'Experience',
      contato: 'Contact',
    },
    sobre: {
      titulo: 'About Me',
      localizacao: 'Location',
      disponibilidade: 'Availability',
      email: 'Email',
      telefone: 'Phone',
    },
    stack: {
      titulo: 'Tech Stack',
      subtitulo: 'Technologies and tools I use',
      categorias: {
        backend: 'Backend',
        banco_dados: 'Database',
        frontend: 'Frontend',
        devops: 'DevOps',
      },
      nivel: 'Level',
    },
    projetos: {
      titulo: 'Projects',
      subtitulo: 'Some of my recent work',
      demo: 'View Demo',
      codigo: 'View Code',
      semLinks: 'Links coming soon',
      tecnologias: 'Technologies',
    },
    experiencia: {
      titulo: 'Professional Experience',
      subtitulo: 'My professional journey',
      atual: 'Current',
      periodo: 'Period',
      tecnologias: 'Technologies',
    },
    contato: {
      titulo: 'Get In Touch',
      subtitulo: "Let's talk about your project",
      nome: 'Name',
      nomePlaceholder: 'Your full name',
      email: 'Email',
      emailPlaceholder: 'your@email.com',
      assunto: 'Subject',
      assuntoPlaceholder: 'What do you want to talk about?',
      mensagem: 'Message',
      mensagemPlaceholder: 'Describe your project or question...',
      enviar: 'Send Message',
      enviando: 'Sending...',
      sucesso: 'Message sent successfully! I will get back to you soon.',
      erro: 'Error sending message. Please try again.',
      erros: {
        nome: 'Name must be between 3 and 100 characters',
        email: 'Invalid email',
        assunto: 'Subject must be between 5 and 200 characters',
        mensagem: 'Message must be between 10 and 5000 characters',
      },
    },
    rodape: {
      desenvolvido: 'Built with React + FastAPI',
      direitos: '© 2025 Argenis Lopez. All rights reserved.',
    },
    comum: {
      carregando: 'Loading...',
      erro: 'Error loading data',
      temaClaro: 'Light Theme',
      temaEscuro: 'Dark Theme',
    },
  },
}

export type Traducoes = typeof traducoes['pt-BR']
